---
version: 0.2
env:
  variables:
    BUILD_INSTANCE_TYPE: "t2.micro"
    AMI_NAME: "my_test_ami"
  parameter-store:
    BUILD_VPC_ID: "VPC_ID"
    BUILD_SUBNET_ID: "SUBNET_ID"
phases:
  install:
    commands:
      - echo "Installing HashiCorp Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/0.12.3/packer_0.12.3_linux_amd64.zip && unzip packer.zip
      - echo "Installing jq..."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
    finally:
      - echo "Installed Packer and jq commands"
  pre_build:
    commands:
      - echo "Validating packer-ec2-ami-build.json"
      - ./packer validate packer-build/packer-ec2-ami-build.json
    finally: 
      - echo " Packer script Validation Completed"
  build:
    commands:
      - echo "Configuring AWS credentials"
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - echo "Building HashiCorp Packer template, amazon-linux_packer-template.json"
      - ./packer build packer-build/packer-ec2-ami-build.json | tee ami_build.log
  post_build:
    commands:
      - echo "AMI build completed on `date`"
      - egrep "${AWS_REGION}\:\sami\-" ami_build.log | cut -d' ' -f2 > ami_id.txt
      # Packer doesn't return non-zero status; we must do that if Packer build failed
      - test -s ami_id.txt || exit 1
      - sed -i.bak "s/<<AMI-ID>>/$(cat ami_id.txt)/g" ami_builder_event.json
      - aws events put-events --entries file://ami_builder_event.json
artifacts:
  files:
    - ami_builder_event.json
    - ami_build.log
  discard-paths: yes