---
# tasks file for base
- name: install all updates
  yum: 
    name: '*'
    state: latest
- name: install ruby
  yum:
    name: ruby
    state: latest
- name: install wget
  yum:
    name: wget
    state: latest
- name: Download codedeploy install script
  command: wget https://aws-codedeploy-ap-south-1.s3.amazonaws.com/latest/install
- name: install the code deploy agent
  command: /bin/bash -x install auto
- name: enable code deploy on boot
  service: 
    name: codedeploy-agent
    enabled: yes

